/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-tertiary-fixed-variant": "#5a4300",
          "surface-container-high": "#e6e8ea",
          "surface": "#f7f9fb",
          "surface-bright": "#f7f9fb",
          "on-background": "#191c1e",
          "tertiary-container": "#936f00",
          "inverse-surface": "#2d3133",
          "on-secondary-container": "#fefcff",
          "error-container": "#ffdad6",
          "on-primary-container": "#f7fff2",
          "secondary-fixed-dim": "#b4c5ff",
          "on-secondary": "#ffffff",
          "on-secondary-fixed": "#00174b",
          "on-tertiary": "#ffffff",
          "tertiary": "#755800",
          "on-surface-variant": "#3e4a3d",
          "error": "#ba1a1a",
          "on-primary-fixed": "#002109",
          "on-primary": "#ffffff",
          "primary-fixed": "#7ffc97",
          "on-error": "#ffffff",
          "on-surface": "#191c1e",
          "secondary-container": "#316bf3",
          "background": "#f7f9fb",
          "primary": "#006b2c",
          "primary-fixed-dim": "#62df7d",
          "on-tertiary-container": "#fffbff",
          "tertiary-fixed-dim": "#f7be1d",
          "primary-container": "#00873a",
          "surface-tint": "#006e2d",
          "on-error-container": "#93000a",
          "on-secondary-fixed-variant": "#003ea8",
          "surface-container-low": "#f2f4f6",
          "surface-variant": "#e0e3e5",
          "tertiary-fixed": "#ffdf9a",
          "inverse-primary": "#62df7d",
          "on-primary-fixed-variant": "#005320",
          "surface-container-lowest": "#ffffff",
          "secondary": "#0051d5",
          "surface-container-highest": "#e0e3e5",
          "secondary-fixed": "#dbe1ff",
          "outline-variant": "#bdcaba",
          "outline": "#6e7b6c",
          "on-tertiary-fixed": "#251a00",
          "surface-container": "#eceef0",
          "surface-dim": "#d8dadc",
          "inverse-on-surface": "#eff1f3"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "fontFamily": {
          "headline": ["Inter", "sans-serif"],
          "body": ["Inter", "sans-serif"],
          "label": ["Inter", "sans-serif"],
          "inter": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
